name: Cam
options:
  bundleIdPrefix: com.wyrtex
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  Cam:
    type: application
    platform: iOS
    sources:
      - path: Cam/Sources
      - path: Cam/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wyrtex.cam
        PRODUCT_NAME: Cam
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Cam/Resources/Info.plist
    info:
      path: Cam/Resources/Info.plist
      properties:
        CFBundleDisplayName: Cam Pro
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UIViewControllerBasedStatusBarAppearance: true
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        NSCameraUsageDescription: Камера нужна для съёмки фото и видео.
        NSMicrophoneUsageDescription: Микрофон нужен для записи звука в видео.
        NSPhotoLibraryAddUsageDescription: Сохранение фото и видео в галерею.
        NSPhotoLibraryUsageDescription: Доступ к галерее для показа последнего снимка.
        NSMotionUsageDescription: Датчики движения нужны для индикатора уровня (горизонт).
